const ARTICLES_LOADED = 'ARTICLES_LOADED';
type ARTICLES_LOADED = typeof ARTICLES_LOADED;

const ADD_ARTICLES = 'ADD_ARTICLES';
type ADD_ARTICLES = typeof ADD_ARTICLES;

export {
  ARTICLES_LOADED,
  ADD_ARTICLES,
};