const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';
const ADD_ARTICLES_REQUEST = 'ADD_ARTICLES_REQUEST';
const ADD_ARTICLES_SUCCESS = 'ADD_ARTICLES_SUCCESS';
const ADD_ARTICLES_FAILURE = 'ADD_ARTICLES_FAILURE';
const UPDATE_ARTICLES_REQUEST = 'UPDATE_ARTICLES_REQUEST';
const UPDATE_ARTICLES_SUCCESS = 'UPDATE_ARTICLES_SUCCESS';
const UPDATE_ARTICLES_FAILURE = 'UPDATE_ARTICLES_FAILURE';

export {
  FETCH_ARTICLES_REQUEST,
  FETCH_ARTICLES_SUCCESS,
  FETCH_ARTICLES_FAILURE,
  ADD_ARTICLES_REQUEST,
  ADD_ARTICLES_SUCCESS,
  ADD_ARTICLES_FAILURE,
  UPDATE_ARTICLES_REQUEST,
  UPDATE_ARTICLES_SUCCESS,
  UPDATE_ARTICLES_FAILURE,
};


